###############################################################################
# @author:      Carl-Eric Wegner
# @affiliation: Küsel Lab - Aquatic Geomicrobiology
#              Friedrich Schiller University of Jena
#
#              carl-eric.wegner@uni-jena.de
#              https://github.com/wegnerce
#              https://www.exploringmicrobes.science
###############################################################################

###############################################################################
# needed packages
###############################################################################
import pandas as pd
import os

###############################################################################
# link to config file
###############################################################################
configfile: "config/config.yaml"

###############################################################################
# needed resources
###############################################################################
ADAPTER = config["adapter-file"]
REF_DB  = config["MARKER"]["ref_db"]

###############################################################################
# relevant parameters input files
###############################################################################
r1_suffix = config["Fastq"]["suffix_R1"]
r2_suffix = config["Fastq"]["suffix_R2"]
PAIRS = [r1_suffix, r2_suffix]

###############################################################################
# extra parameters used tools
###############################################################################
BBDUK     = config["EXTRA"]["bbduk"]
MERGE     = config["EXTRA"]["merge"]
FILTERING = config["EXTRA"]["filtering"]

###############################################################################
# read sample names from samples.tsv
###############################################################################
SAMPLES = pd.read_table(config["sample-file"], header=0, sep="\t", index_col=0)
raw_data_dir = config["rawdata-dir"]

###############################################################################
rule all:
    input:
        # 6 | Taxonomic assignment with vsearch and sintax
        "results/06_TAXONOMY/sintax_clean.txt",
        "results/06_TAXONOMY/sintax.txt",
        # 5 | OTU clustering + OTU table generation
        "results/05_OTU_CLUSTERING/otutab.txt",
        "results/05_OTU_CLUSTERING/otus.fasta",
        # 4 | Dereplication with vsearch
        "results/04_UNIQUE/unique.fasta",
        # 3 | Additional quality filtering with vsearch
        "results/03_STRIPPED_FILTERED/stripped_filtered.fasta",
        # 2b| Concatenate merged read pairs
        "results/02_MERGED/all_merged.fastq",
        # 2 | Merging of read pairs with vsearch
        expand("results/02_MERGED/{sample}_merged.fastq",
               sample=SAMPLES.index),
        # 1 + 2b | QC before adapter removal and after merging
        expand("logs/fastqc/raw/{sample}_{pair}_fastqc.html",
               sample=SAMPLES.index, pair=PAIRS),
        expand("logs/fastqc/merged/{sample}_merged_fastqc.html",
               sample=SAMPLES.index),

###############################################################################
# needed rules
###############################################################################
include: "rules/qc.smk"
include: "rules/vsearch.smk"
